sudo: reqyured
language: elixir
elixir:
  - 1.11.3
otp_release:
  - 22.2.6

addons:
  postgres: '9.4'

services:
  - postgressql

script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobelow --config
  - MIX_ENV=test mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
