sudo: reqyured
language: elixir
elixir:
  - 1.11.3
otp_release:
  - 22.2.6

addons:
  postgres: '9.4'

services:
  - postgressql

script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobelow --config
  - MIX_ENV=test mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy: # Add this 'deploy' stage description
  stage: deploy
  script:
   - git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
   - git push -f gigalixir HEAD:refs/heads/master
 only:
    - master

